=== LukasFlorian/StudyBuddy/labs/Labor2/Vorlesungsplan/Vorlesungsplan.dtd
<!ELEMENT vorlesungsplan (vorlesung+, raumplan+)>
<!ELEMENT vorlesung (titel, dozent, zeit)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT dozent (#PCDATA)>
<!ELEMENT zeit (#PCDATA)>
<!ELEMENT raumplan (raumBezeichnung, raumBeschreibung)>
<!ELEMENT raumBezeichnung (#PCDATA)>
<!ELEMENT raumBeschreibung (#PCDATA)>

=== LukasFlorian/StudyBuddy/labs/Labor2/Vorlesungsplan/Vorlesungsplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vorlesungsplan SYSTEM "./Vorlesungsplan.dtd">
<vorlesungsplan xmlns:modul="http://example.com/modul"
                xmlns:raum="http://example.com/raum">
    <modul:vorlesung>
        <titel>Web Engineering</titel>
        <dozent>Prof. Schneider</dozent>
        <zeit>Mo 10:00 - 12:00</zeit>
    </modul:vorlesung>
    <raum:raumplan>
        <raumBezeichnung>H222</raumBezeichnung>
        <raumBeschreibung>HÃ¶rsaal</raumBeschreibung>
    </raum:raumplan>
</vorlesungsplan>
